import { Inter } from "next/font/google";
import "./globals.css";
import Nav from './components/nav';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Shop E-Commerce",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      {/* nav */}
      <Nav/>
      <div className="bg-base-100">
        {children}
      </div>
        
        </body>
    </html>
  );
}
